### ISSUE TITLE
Adicionar pastas e artefatos seguindo o padrão PDDS

### ISSUE THREAD

**Issue by lauro-ss** [marcosdosea/AgendeMe#1]

**Comment by viniVN7** [comment]
Pastas que deverão ser adicionadas e seus respectivos artefatos:
1. Gerenciamento 
- documento de visão

2. ProcessosNegocio
- modelos BPMN 

3. Requisitos
- lista de requisitos funcionais e não funcionais 
- documentos de casos de uso 
- protótipos de alta fidelidade 

4. AnaliseProjeto
- arquivo do StarUML contendo modelo de casos de uso, diagramas de estados, modelos de análise e modelos de projeto

5. Codigo

6. Testes

**Comment by lauro-ss** [comment]
> Pastas que deverão ser adicionadas e seus respectivos artefatos:
> 
> 1. Gerenciamento
> 
> * documento de visão
> 
> 2. ProcessosNegocio
> 
> * modelos BPMN
> 
> 3. Requisitos
> 
> * lista de requisitos funcionais e não funcionais
> * documentos de casos de uso
> * protótipos de alta fidelidade
> 
> 4. AnaliseProjeto
> 
> * arquivo do StarUML contendo modelo de casos de uso, diagramas de estados, modelos de análise e modelos de projeto
> * arquivo do MySQL Workbench
> 5. Codigo
> 6. Testes
