### ISSUE TITLE
Renomear casos de uso detalhados 

### ISSUE THREAD

**Issue by viniVN7** [marcosdosea/AgendeMe#133]
Devido as alterações do nome de alguns casos de uso, deve-se analisar os documentos de detalhamento dos mesmos e verificar se os nomes correspondem com os nomes dos casos de uso atuais.

**Comment by Gabrielx47** [comment]
Fazer a verificação dos nomes dos casos de usos, sendo que o objetivo é verificar se os mesmos estão iguais no documento "Casos de Uso e Requisitos" e na pasta quem possui o detalhamento de cada um deles. Sendo assim, em caso de divergências, fazer as modificações corretivas.
