### ISSUE TITLE
Atualizar o arquivo AgendeMe.mdj

### ISSUE THREAD

**Issue by Gabrielx47** [marcosdosea/AgendeMe#183]
Atualização no diagrama de classe:
- UC-Manter Orgao Publico: 
   1) Retirar o relacionamento entre as entidades "OrgaoPublico" e "Atendente" .
   2) Adicionar o relacionamento N para N entre as entidades "OrgaoPublico" e "Cidadao".
- DER:
   1) Fazer as devidas atualizações para que as alterações feitas no caso de uso acima seja refletida        no DER.

**Comment by lauro-ss** [comment]
Esse relacionamento entre Atendente e Orgao Publico está corretos! Não a necessidade de remover a adicionar o relacionamento de cidadao com orgao publico, fica redundate e incorreto.

O relacionamento adicionado entre Cidadao e Orgao Publico somente existe no modelo de banco, pois pela regra de mapeamento, todas as entidades derivadas (profissional, atendente, gestor do orgao, gestor da prefeitura, administrador) estão compostos em um atributo do tipo ENUM no modelo de banco na tabela Cidadao, seguindo a estratégia de mapeamento superclasse (Cidadao) com muitos dados e poucos dados na subclasse (Atendente).

A entidade Atendente é uma herança da entidade Cidadao. Onde todo Atendente é um cidadão, mas nem todo cidadão é um atendente. O relacionamento N pra N só existe entre Atendente e Orgao.

![image](https://user-images.githubusercontent.com/69280619/190018724-dd05e1b9-4309-4559-907f-541ce1199bfb.png)

Essa seta representa a herança no modelo UML, veja que todas essas entidades (profissional, atendente, gestor do orgao, gestor da prefeitura, administrador) herdam de cidadao, logo, todos são cidadãos, e por isso os relacionamentos associados a entidade Atendente estão associados ao Cidadao no modelo de banco. O Modelo de Banco reflete um mapeamento do modelo DER do UML, e não o inverso.
